### PR TITLE
Release 0.3.0

### PR DESCRIPTION
**Pull request by larsbutler**

### CODE REVIEW

**Comment by tomplex** [comment]
This looks great! It will be awesome to be able to manage releases directly from the github page. If I understand this MR isn't strictly related to the 0.3.0 release but is just enabling the workflow?

**Review by achapkowski — APPROVED** [review]
Looks great!

**Comment by larsbutler** [comment]
@tomplex No, this will actually do the release as well. I probably could have done it as a separate PR, but it's done now.

**Comment by larsbutler** [comment]
0.3.0 is released to PyPI now.

**Pull request merged**
