### PR TITLE
Fix Python3.3 TravisCI build

### PR DESCRIPTION
**Pull request by larsbutler**
This issue just occurred:
https://travis-ci.org/geomet/geomet/jobs/462352763.

I suspect this is due to a stale install of pip. It should help to always upgrade `pip` in TravisCI build.

### CODE REVIEW

**Comment by larsbutler** [comment]
So, I just found out that Python3.3 received an end-of-life in September 2017: https://www.python.org/dev/peps/pep-0398/#x-end-of-life. I think the solution here is to just drop support for it.

**Comment by tomplex** [comment]
@larsbutler, I totally agree with removing Python3 - if it's EOL, then supporting it seems like it's not worth the time. It might be worth, however, adding some sort of checking in the `setup.py` to ensure that people using Python3.3 don't install versions of `geomet` that weren't tested against Python3.3. We could also add a note that Python3.3 support was dropped after version x, so new users of `geomet` stuck on 3.3 can specifically install compatible versions of the package.

**Comment by larsbutler** [comment]
@tomplex How does this look? Unfortunately, adding `python_requires` wasn't sufficient to physically prevent an install with Python3.3 so I added the version check+exception to cover that.

**Comment by tomplex** [comment]
Hey @larsbutler, looks good to me. I'll merge if you're ready.

**Comment by larsbutler** [comment]
@tomplex Yep, go for it.

**Pull request merged**
