### PR TITLE
Add support for Python3.12

### LINKED ISSUE #92: Tests fail with Python 3.12
Attempting a build against Python 3.12 b3 fails some tests:

```
======================================================================
ERROR: test_malformed_wkt_no_ending_paren (geomet.tests.wkt_test.GeometryCollectionLoadsTestCase.test_malformed_wkt_no_ending_paren)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/geomet-1.0.0/geomet/tests/wkt_test.py", line 1219, in test_malformed_wkt_no_ending_paren
    wkt.loads(mp)
  File "/builddir/build/BUILD/geomet-1.0.0/geomet/wkt.py", line 147, in loads
    result = importer(tokens, string)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builddir/build/BUILD/geomet-1.0.0/geomet/wkt.py", line 638, in _load_geometrycollection
    geom = load_func(tokens, string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable
======================================================================
FAIL: test_raises_unmatched_paren (geomet.tests.wkt_test.LineStringLoadsTestCase.test_raises_unmatched_paren)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/geomet-1.0.0/geomet/tests/wkt_test.py", line 324, in test_raises_unmatched_paren
    self.assertEqual('Invalid WKT: `LINESTRING (0.0 1.0`',
AssertionError: 'Invalid WKT: `LINESTRING (0.0 1.0`' != "could not convert string to float: ''"
- Invalid WKT: `LINESTRING (0.0 1.0`
+ could not convert string to float: ''
======================================================================
FAIL: test_malformed_wkt_misbalanced_parens (geomet.tests.wkt_test.MultiPointLoadsTestCase.test_malformed_wkt_misbalanced_parens)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/geomet-1.0.0/geomet/tests/wkt_test.py", line 521, in test_malformed_wkt_misbalanced_parens
    self.assertEqual(expected, str(ar.exception))
AssertionError: 'Invalid WKT: `MULTIPOINT ((0 0), (0 1)`' != "could not convert string to float: ''"
- Invalid WKT: `MULTIPOINT ((0 0), (0 1)`
+ could not convert string to float: ''
======================================================================
FAIL: test_raises_unmatched_paren (geomet.tests.wkt_test.PointLoadsTestCase.test_raises_unmatched_paren)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/geomet-1.0.0/geomet/tests/wkt_test.py", line 245, in test_raises_unmatched_paren
    self.assertEqual('Invalid WKT: `POINT (0.0 1.0`',
AssertionError: 'Invalid WKT: `POINT (0.0 1.0`' != "could not convert string to float: ''"
- Invalid WKT: `POINT (0.0 1.0`
+ could not convert string to float: ''
======================================================================
FAIL: test_raises_unmatched_paren (geomet.tests.wkt_test.PolygonLoadsTestCase.test_raises_unmatched_paren)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/geomet-1.0.0/geomet/tests/wkt_test.py", line 431, in test_raises_unmatched_paren
    self.assertEqual(
AssertionError: 'Invalid WKT: `POLYGON ((0.0 0.0, 1.0 4.0, 4.0 1.0, 0.0 0.0)`' != "could not convert string to float: ''"
- Invalid WKT: `POLYGON ((0.0 0.0, 1.0 4.0, 4.0 1.0, 0.0 0.0)`
+ could not convert string to float: ''
Could not read Geopackage geometry because of errors: Envelope indicator must be between 0-4
Could not read Geopackage geometry because of errors: Geopackage version must be 0
```

It appears that the convenient tokenizer has changed behaviour a bit.

### PR DESCRIPTION
**Pull request by larsbutler**
Fixes #92 and #104.

### CODE REVIEW

**Review by achapkowski — COMMENTED** [review]
It seems the 3.12 unit test fail

**Comment by larsbutler** [comment]
> It seems the 3.12 unit test fail

Indeed. I had forgotten about the tokenization change in Python 3.12, but seems like an easy fix (we just need to ignore some empty string tokens; not a significant change to the WKT parsing logic).

**Comment by larsbutler** [comment]
I think we're good now. @achapkowski Do these changes look okay to you?

**Review by achapkowski — APPROVED** [review]

**Comment by larsbutler** [comment]
Thanks @achapkowski!

**Pull request merged**
